docker-image: dbscan-benchmarks-srrdbscan
module: srrdbscan
name: srrdbscan
constructor: SRRDBSCAN
args:
  - [0.01] #[0.1, 0.3, 0.5, 0.7, 0.9] # failure probability
  - [5] # memory usage (for small datasets, 0.1 is a good choice as well)
  - [56] # number of threads
  - [1] # shrinkage parameter (fraction of repetitions inspected)